/// @description Initialize Manager

LOCKED_DOOR = 0;
PILLS_PICKED_UP = 1;
GUN_PICKED_UP = 2;
GUN_FIRED = 3;
PILLS_TAKEN = 4;
BAT_PICKED_UP = 5;
FOOD_PICKED_UP = 6;
LADDER_APPROACHED = 7;
KEY_PICKED_UP = 8;
WAKE_UP = 9;
LEAVE_HUB = 10;
ENEMY_ENCOUNTERED = 11;
ENEMY_KNOCKED_OUT = 12;
